using Mutagen.Bethesda;
using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.Synthesis;

namespace FO4HeelSoundPatcher;

public static class Program
{
    public static Lazy<Settings> PatchSettings = null!;

    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .AddPatch<IFallout4Mod, IFallout4ModGetter>(RunPatch)
            .SetAutogeneratedSettings("Settings", "settings.json", out PatchSettings)
            .AddRunnabilityCheck(CheckRunnability)
            .SetTypicalOpen(GameRelease.Fallout4, "HeelSounds.esp")
            .Run(args);
    }

    /// <summary>
    /// Cheap up-front check so the user finds out before the pipeline starts, not after several
    /// minutes of other patchers. Keep it fast - Synthesis calls this often.
    /// </summary>
    public static void CheckRunnability(IRunnabilityState state)
    {
        var soundModKey = PatchSettings.Value.Sound.HeelFootstepSet.FormKey.ModKey;
        if (soundModKey.IsNull) return;

        var listed = state.LoadOrder.ListedOrder.Any(listing => listing.ModKey == soundModKey);
        if (listed) return;

        throw new InvalidOperationException(
            $"'{soundModKey}' is not in the load order, but the configured heel footstep set " +
            $"({PatchSettings.Value.Sound.HeelFootstepSet.FormKey}) comes from it. " +
            "Install/enable it, or pick a footstep set from a plugin you do have.");
    }

    public static void RunPatch(IPatcherState<IFallout4Mod, IFallout4ModGetter> state)
    {
        var patcher = new HeelSoundPatcher(state, PatchSettings.Value);
        patcher.Run();
    }
}
